#!/usr/bin/env python3
"""
Convert GIF animation to C PROGMEM byte array for 1-bit monochrome displays.

Output style matches:
  #define XXX_FRAME_WIDTH ...
  #define XXX_FRAME_HEIGHT ...
  #define XXX_FRAME_BYTES (((XXX_FRAME_WIDTH + 7) / 8) * XXX_FRAME_HEIGHT)
  const byte PROGMEM xxx_frames[][XXX_FRAME_BYTES] = { ... };
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

try:
    from PIL import Image, ImageOps  # type: ignore
except Exception:
    Image = None  # type: ignore
    ImageOps = None  # type: ignore


@dataclass
class ConvertOptions:
    name: str
    width: int
    height: int
    threshold: int
    invert: bool
    resize_filter: str
    dedupe: bool
    bg: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert GIF to C byte array.")
    parser.add_argument("input", type=Path, help="Input GIF path")
    parser.add_argument(
        "-o", "--output", type=Path, required=True, help="Output .h/.c file path"
    )
    parser.add_argument(
        "-n",
        "--name",
        required=True,
        help="Base symbol name, e.g. wifi => wifi_frames/WIFI_FRAME_WIDTH",
    )
    parser.add_argument("-W", "--width", type=int, default=32, help="Target width")
    parser.add_argument("-H", "--height", type=int, default=32, help="Target height")
    parser.add_argument(
        "-t",
        "--threshold",
        type=int,
        default=128,
        help="Threshold 0-255, lower is more black",
    )
    parser.add_argument(
        "--invert",
        action="store_true",
        help="Invert black/white before packing bits",
    )
    parser.add_argument(
        "--resize",
        choices=["nearest", "bilinear", "bicubic", "lanczos"],
        default="nearest",
        help="Resize filter",
    )
    parser.add_argument(
        "--dedupe",
        action="store_true",
        help="Remove consecutive duplicate frames",
    )
    parser.add_argument(
        "--bg",
        type=int,
        default=255,
        help="Background gray (0-255) for transparent pixels, default white",
    )
    return parser.parse_args()


def get_resample(mode: str) -> int:
    if Image is None:
        raise RuntimeError("Pillow is required. Run: pip install -r tools/gif_to_c/requirements.txt")
    if mode == "nearest":
        return Image.Resampling.NEAREST
    if mode == "bilinear":
        return Image.Resampling.BILINEAR
    if mode == "bicubic":
        return Image.Resampling.BICUBIC
    return Image.Resampling.LANCZOS


def frame_to_mono_bytes(frame: Image.Image, opts: ConvertOptions) -> List[int]:
    if Image is None or ImageOps is None:
        raise RuntimeError("Pillow is required. Run: pip install -r tools/gif_to_c/requirements.txt")
    # Composite transparency on background.
    rgba = frame.convert("RGBA")
    bg = Image.new("RGBA", rgba.size, (opts.bg, opts.bg, opts.bg, 255))
    merged = Image.alpha_composite(bg, rgba).convert("L")

    # Resize to target.
    merged = merged.resize((opts.width, opts.height), resample=get_resample(opts.resize_filter))

    # Optional invert.
    if opts.invert:
        merged = ImageOps.invert(merged)

    # Threshold to 1-bit logic, then pack row-major, bit7 first.
    pixels = merged.load()
    bytes_per_row = (opts.width + 7) // 8
    out: List[int] = [0] * (bytes_per_row * opts.height)

    for y in range(opts.height):
        for x in range(opts.width):
            val = pixels[x, y]
            on = val < opts.threshold  # dark pixel => bit=1
            if on:
                idx = y * bytes_per_row + (x // 8)
                bit_pos = 7 - (x % 8)
                out[idx] |= 1 << bit_pos
    return out


def sanitize_symbol(name: str) -> str:
    cleaned = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            cleaned.append(ch.lower())
        else:
            cleaned.append("_")
    s = "".join(cleaned).strip("_")
    return s or "icon"


def render_c(opts: ConvertOptions, frames: List[List[int]]) -> str:
    base = sanitize_symbol(opts.name)
    upper = base.upper()
    frame_bytes = ((opts.width + 7) // 8) * opts.height

    lines: List[str] = []
    lines.append("// Generated by tools/gif_to_c/gif_to_c.py")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append(f"#define {upper}_FRAME_WIDTH {opts.width}")
    lines.append(f"#define {upper}_FRAME_HEIGHT {opts.height}")
    lines.append(f"#define {upper}_FRAME_DELAY 42")
    lines.append(
        f"#define {upper}_FRAME_BYTES ((({upper}_FRAME_WIDTH + 7) / 8) * {upper}_FRAME_HEIGHT)"
    )
    lines.append("")
    lines.append(f"const byte PROGMEM {base}_frames[][{upper}_FRAME_BYTES] = {{")

    for arr in frames:
        if len(arr) != frame_bytes:
            raise RuntimeError("Packed frame size mismatch")
        content = ",".join(str(v) for v in arr)
        lines.append(f"  {{{content}}},")

    lines.append("};")
    lines.append("")
    lines.append(
        f"constexpr size_t {upper}_FRAME_COUNT = sizeof({base}_frames) / sizeof({base}_frames[0]);"
    )
    lines.append(
        f"static_assert({upper}_FRAME_COUNT > 0, \"{base}_frames must not be empty\");"
    )
    lines.append(
        f"static_assert(sizeof({base}_frames[0]) == {upper}_FRAME_BYTES,"
    )
    lines.append(
        f"              \"{base}_frames frame size does not match {upper}_FRAME_WIDTH/{upper}_FRAME_HEIGHT\");"
    )
    lines.append("")
    return "\n".join(lines)


def collect_frames_from_gif(input_path: Path, opts: ConvertOptions) -> List[List[int]]:
    if Image is None:
        raise RuntimeError(
            "Missing dependency: Pillow. Install with: pip install -r tools/gif_to_c/requirements.txt"
        )
    if not input_path.exists():
        raise RuntimeError(f"Input GIF not found: {input_path}")
    if opts.width <= 0 or opts.height <= 0:
        raise RuntimeError("Width and height must be > 0")

    img = Image.open(input_path)
    frames: List[List[int]] = []
    prev: List[int] | None = None

    frame_index = 0
    while True:
        packed = frame_to_mono_bytes(img.copy(), opts)
        if not (opts.dedupe and prev == packed):
            frames.append(packed)
            prev = packed
        frame_index += 1
        try:
            img.seek(frame_index)
        except EOFError:
            break

    if not frames:
        raise RuntimeError("No frames generated.")
    return frames


def collect_frames_from_image(input_path: Path, opts: ConvertOptions) -> List[List[int]]:
    if Image is None:
        raise RuntimeError(
            "Missing dependency: Pillow. Install with: pip install -r tools/gif_to_c/requirements.txt"
        )
    if not input_path.exists():
        raise RuntimeError(f"Input image not found: {input_path}")
    if opts.width <= 0 or opts.height <= 0:
        raise RuntimeError("Width and height must be > 0")

    img = Image.open(input_path)
    packed = frame_to_mono_bytes(img.copy(), opts)
    return [packed]


def convert_gif_to_c(input_path: Path, output_path: Path, opts: ConvertOptions) -> Tuple[int, str]:
    frames = collect_frames_from_gif(input_path, opts)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_c(opts, frames), encoding="utf-8")
    return len(frames), sanitize_symbol(opts.name)


def convert_image_to_c(input_path: Path, output_path: Path, opts: ConvertOptions) -> Tuple[int, str]:
    frames = collect_frames_from_image(input_path, opts)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_c(opts, frames), encoding="utf-8")
    return len(frames), sanitize_symbol(opts.name)


def main() -> None:
    args = parse_args()
    if Image is None:
        raise SystemExit("Missing dependency: Pillow. Install with: pip install -r tools/gif_to_c/requirements.txt")
    opts = ConvertOptions(
        name=args.name,
        width=args.width,
        height=args.height,
        threshold=max(0, min(255, args.threshold)),
        invert=args.invert,
        resize_filter=args.resize,
        dedupe=args.dedupe,
        bg=max(0, min(255, args.bg)),
    )

    try:
        frame_count, _ = convert_gif_to_c(args.input, args.output, opts)
    except RuntimeError as exc:
        raise SystemExit(str(exc))
    print(f"Done: {args.output} | frames={frame_count} | size={opts.width}x{opts.height}")


if __name__ == "__main__":
    main()
